# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShiborRate',
            fields=[
                ('pushDate', models.DateTimeField(primary_key=True, serialize=False)),
                ('oneNight', models.DecimalField(decimal_places=6, max_digits=10)),
                ('oneWeek', models.DecimalField(decimal_places=6, max_digits=10)),
                ('twoWeek', models.DecimalField(decimal_places=6, max_digits=10)),
                ('oneMonth', models.DecimalField(decimal_places=6, max_digits=10)),
                ('threeMonth', models.DecimalField(decimal_places=6, max_digits=10)),
                ('sixMonth', models.DecimalField(decimal_places=6, max_digits=10)),
                ('nineMonth', models.DecimalField(decimal_places=6, max_digits=10)),
                ('oneYear', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
    ]
